back:
    resource: "@BackBundle/Resources/config/routing.yml"
    prefix:   /admin

user:
    resource: "@UserBundle/Resources/config/routing.yml"
    prefix:   /user

front:
    resource: "@FrontBundle/Resources/config/routing.yml"
    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

# app/config/routing.yml
fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile
client_commentairesAnc:
    resource: "@FrontBundle/Resources/config/routing/commentairesAnc.yml"
    prefix:   /client/commentairesAnc

commercial_annonces:
    resource: "@BackBundle/Resources/config/routing/annonces.yml"
    prefix:   /commercial/annonces

client_annonces:
    resource: "@FrontBundle/Resources/config/routing/annonces.yml"
    prefix:   /client/annonces

fos_message:
    resource: "@FOSMessageBundle/Resources/config/routing.xml"
    prefix: /messages